name: Deploy on server

on:
  push:
    branches: [main,test]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Get branch name"
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: "Deployed site"
      run: curl
        -X POST
        -H "Content-Type:application/json"
        -d '{"branch":"${{ github.head_ref }}", "${{ secrets.PARAM1 }}":"${{ secrets.VALUE1 }}", "${{ secrets.PARAM2 }}":"${{ secrets.VALUE2 }}"}' ${{ secrets.FLYPO_TEST_HOOK }}
